name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies for Python
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements/common.txt ]; then pip install -r requirements/common.txt; fi
          if [ -f requirements/dev.txt ]; then pip install -r requirements/dev.txt; fi
      - name: Install dependencies for OpenMPI
        run: |
          apt install openmpi-bin openmpi-common libopenmpi-dev
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  unit_tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements/common.txt ]; then pip install -r requirements/common.txt; fi
          if [ -f requirements/dev.txt ]; then pip install -r requirements/dev.txt; fi
      - name: Unit test
        run: |
          coverage run -m pytest test/unit
          coverage xml
          echo "Code coverage report:"
          coverage report
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage.xml
          path: ./coverage.xml
